# addons:
#   postgresql: 10.3
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_script:
  - gem install bundler
  - bin/rails db:create
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
dist: trusty
env:
  global:
    - CC_TEST_REPORTER_ID=daac262d167165ece12aaa187a30d5b9f63d6782941804702b5eb6dfa15763c0
language: ruby
notifications:
  - false
rvm:
  - 2.5.0
script:
  - bundle exec rspec spec
  - bundle exec rails db:migrate RAILS_ENV=test
services:
  - postgresql: "10.3"
